
// This file has been generated by the GUI designer. Do not modify.

public partial class MainMenu
{
	private global::Gtk.VBox ZT_MainVBox1;
	
	private global::Gtk.VBox ZT_SubVBox1;
	
	private global::Gtk.HBox ZT_SVB1_S2_HBox1;
	
	private global::Gtk.Button ZT_SVB1_S2_Button1;
	
	private global::Gtk.VBox ZT_SubVBox2;
	
	private global::Gtk.HBox ZT_SVB2_S2_HBox1;
	
	private global::Gtk.Button ZT_SVB2_S2_Button1;
	
	private global::Gtk.VBox ZT_SubVBox3;
	
	private global::Gtk.HBox ZT_SVB3_S2_HBox1;
	
	private global::Gtk.Button ZT_SVB3_S2_Button1;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainMenu
		this.WidthRequest = 600;
		this.HeightRequest = 650;
		this.Name = "MainMenu";
		this.Title = global::Mono.Unix.Catalog.GetString ("Zester Tool : Main Menu");
		this.Icon = global::Stetic.IconLoader.LoadIcon (this, "gtk-preferences", global::Gtk.IconSize.Menu);
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.Resizable = false;
		this.AllowShrink = true;
		this.DestroyWithParent = true;
		this.Gravity = ((global::Gdk.Gravity)(10));
		// Container child MainMenu.Gtk.Container+ContainerChild
		this.ZT_MainVBox1 = new global::Gtk.VBox ();
		this.ZT_MainVBox1.Name = "ZT_MainVBox1";
		this.ZT_MainVBox1.Spacing = 6;
		// Container child ZT_MainVBox1.Gtk.Box+BoxChild
		this.ZT_SubVBox1 = new global::Gtk.VBox ();
		this.ZT_SubVBox1.Name = "ZT_SubVBox1";
		this.ZT_SubVBox1.Spacing = 6;
		// Container child ZT_SubVBox1.Gtk.Box+BoxChild
		this.ZT_SVB1_S2_HBox1 = new global::Gtk.HBox ();
		this.ZT_SVB1_S2_HBox1.Name = "ZT_SVB1_S2_HBox1";
		this.ZT_SVB1_S2_HBox1.Spacing = 6;
		// Container child ZT_SVB1_S2_HBox1.Gtk.Box+BoxChild
		this.ZT_SVB1_S2_Button1 = new global::Gtk.Button ();
		this.ZT_SVB1_S2_Button1.WidthRequest = 200;
		this.ZT_SVB1_S2_Button1.CanFocus = true;
		this.ZT_SVB1_S2_Button1.Name = "ZT_SVB1_S2_Button1";
		this.ZT_SVB1_S2_Button1.UseUnderline = true;
		this.ZT_SVB1_S2_Button1.Label = global::Mono.Unix.Catalog.GetString ("New Project Config");
		this.ZT_SVB1_S2_HBox1.Add (this.ZT_SVB1_S2_Button1);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.ZT_SVB1_S2_HBox1 [this.ZT_SVB1_S2_Button1]));
		w1.Position = 0;
		w1.Fill = false;
		this.ZT_SubVBox1.Add (this.ZT_SVB1_S2_HBox1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.ZT_SubVBox1 [this.ZT_SVB1_S2_HBox1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		w2.Padding = ((uint)(125));
		this.ZT_MainVBox1.Add (this.ZT_SubVBox1);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.ZT_MainVBox1 [this.ZT_SubVBox1]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child ZT_MainVBox1.Gtk.Box+BoxChild
		this.ZT_SubVBox2 = new global::Gtk.VBox ();
		this.ZT_SubVBox2.Name = "ZT_SubVBox2";
		this.ZT_SubVBox2.Spacing = 6;
		// Container child ZT_SubVBox2.Gtk.Box+BoxChild
		this.ZT_SVB2_S2_HBox1 = new global::Gtk.HBox ();
		this.ZT_SVB2_S2_HBox1.Name = "ZT_SVB2_S2_HBox1";
		this.ZT_SVB2_S2_HBox1.Spacing = 6;
		// Container child ZT_SVB2_S2_HBox1.Gtk.Box+BoxChild
		this.ZT_SVB2_S2_Button1 = new global::Gtk.Button ();
		this.ZT_SVB2_S2_Button1.WidthRequest = 200;
		this.ZT_SVB2_S2_Button1.Sensitive = false;
		this.ZT_SVB2_S2_Button1.CanFocus = true;
		this.ZT_SVB2_S2_Button1.Name = "ZT_SVB2_S2_Button1";
		this.ZT_SVB2_S2_Button1.UseUnderline = true;
		this.ZT_SVB2_S2_Button1.Label = global::Mono.Unix.Catalog.GetString ("Create Daily Report");
		this.ZT_SVB2_S2_HBox1.Add (this.ZT_SVB2_S2_Button1);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.ZT_SVB2_S2_HBox1 [this.ZT_SVB2_S2_Button1]));
		w4.Position = 0;
		w4.Fill = false;
		this.ZT_SubVBox2.Add (this.ZT_SVB2_S2_HBox1);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.ZT_SubVBox2 [this.ZT_SVB2_S2_HBox1]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		this.ZT_MainVBox1.Add (this.ZT_SubVBox2);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.ZT_MainVBox1 [this.ZT_SubVBox2]));
		w6.Position = 1;
		w6.Expand = false;
		w6.Fill = false;
		// Container child ZT_MainVBox1.Gtk.Box+BoxChild
		this.ZT_SubVBox3 = new global::Gtk.VBox ();
		this.ZT_SubVBox3.Name = "ZT_SubVBox3";
		this.ZT_SubVBox3.Spacing = 6;
		// Container child ZT_SubVBox3.Gtk.Box+BoxChild
		this.ZT_SVB3_S2_HBox1 = new global::Gtk.HBox ();
		this.ZT_SVB3_S2_HBox1.Name = "ZT_SVB3_S2_HBox1";
		this.ZT_SVB3_S2_HBox1.Spacing = 6;
		// Container child ZT_SVB3_S2_HBox1.Gtk.Box+BoxChild
		this.ZT_SVB3_S2_Button1 = new global::Gtk.Button ();
		this.ZT_SVB3_S2_Button1.WidthRequest = 200;
		this.ZT_SVB3_S2_Button1.Sensitive = false;
		this.ZT_SVB3_S2_Button1.CanFocus = true;
		this.ZT_SVB3_S2_Button1.Name = "ZT_SVB3_S2_Button1";
		this.ZT_SVB3_S2_Button1.UseUnderline = true;
		this.ZT_SVB3_S2_Button1.Label = global::Mono.Unix.Catalog.GetString ("Manage Project Configs");
		this.ZT_SVB3_S2_HBox1.Add (this.ZT_SVB3_S2_Button1);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.ZT_SVB3_S2_HBox1 [this.ZT_SVB3_S2_Button1]));
		w7.Position = 0;
		w7.Fill = false;
		this.ZT_SubVBox3.Add (this.ZT_SVB3_S2_HBox1);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.ZT_SubVBox3 [this.ZT_SVB3_S2_HBox1]));
		w8.Position = 0;
		w8.Expand = false;
		w8.Fill = false;
		w8.Padding = ((uint)(125));
		this.ZT_MainVBox1.Add (this.ZT_SubVBox3);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.ZT_MainVBox1 [this.ZT_SubVBox3]));
		w9.Position = 2;
		w9.Expand = false;
		w9.Fill = false;
		this.Add (this.ZT_MainVBox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 600;
		this.DefaultHeight = 650;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.ZT_SVB1_S2_Button1.Clicked += new global::System.EventHandler (this.OnZTSVB1S2Button1Clicked);
	}
}
