
// This file has been generated by the GUI designer. Do not modify.

public partial class MainMenu
{
	private global::Gtk.VBox ZT_MainVBox1;
	private global::Gtk.VBox ZT_SubVBox1;
	private global::Gtk.Fixed fixed8;
	private global::Gtk.HBox ZT_SVB1_S2_HBox1;
	private global::Gtk.Fixed fixed1;
	private global::Gtk.Button ZT_SVB1_S2_Button1;
	private global::Gtk.Fixed fixed2;
	private global::Gtk.Fixed fixed11;
	private global::Gtk.VBox ZT_SubVBox2;
	private global::Gtk.Fixed fixed9;
	private global::Gtk.HBox ZT_SVB2_S2_HBox1;
	private global::Gtk.Fixed fixed4;
	private global::Gtk.Button ZT_SVB2_S2_Button1;
	private global::Gtk.Fixed fixed5;
	private global::Gtk.Fixed fixed10;
	private global::Gtk.VBox ZT_SubVBox3;
	private global::Gtk.Fixed fixed12;
	private global::Gtk.HBox ZT_SVB3_S2_HBox1;
	private global::Gtk.Fixed fixed6;
	private global::Gtk.Button ZT_SVB3_S2_Button1;
	private global::Gtk.Fixed fixed7;
	private global::Gtk.Fixed fixed13;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainMenu
		this.WidthRequest = 600;
		this.HeightRequest = 650;
		this.Name = "MainMenu";
		this.Title = global::Mono.Unix.Catalog.GetString ("Zester Tool : Main Menu");
		this.Icon = global::Stetic.IconLoader.LoadIcon (this, "gtk-preferences", global::Gtk.IconSize.Menu);
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.Resizable = false;
		this.AllowShrink = true;
		this.DestroyWithParent = true;
		// Container child MainMenu.Gtk.Container+ContainerChild
		this.ZT_MainVBox1 = new global::Gtk.VBox ();
		this.ZT_MainVBox1.Name = "ZT_MainVBox1";
		this.ZT_MainVBox1.Spacing = 6;
		// Container child ZT_MainVBox1.Gtk.Box+BoxChild
		this.ZT_SubVBox1 = new global::Gtk.VBox ();
		this.ZT_SubVBox1.Name = "ZT_SubVBox1";
		this.ZT_SubVBox1.Spacing = 6;
		// Container child ZT_SubVBox1.Gtk.Box+BoxChild
		this.fixed8 = new global::Gtk.Fixed ();
		this.fixed8.HeightRequest = 60;
		this.fixed8.Name = "fixed8";
		this.fixed8.HasWindow = false;
		this.ZT_SubVBox1.Add (this.fixed8);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.ZT_SubVBox1 [this.fixed8]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child ZT_SubVBox1.Gtk.Box+BoxChild
		this.ZT_SVB1_S2_HBox1 = new global::Gtk.HBox ();
		this.ZT_SVB1_S2_HBox1.Name = "ZT_SVB1_S2_HBox1";
		this.ZT_SVB1_S2_HBox1.Spacing = 6;
		// Container child ZT_SVB1_S2_HBox1.Gtk.Box+BoxChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		this.ZT_SVB1_S2_HBox1.Add (this.fixed1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.ZT_SVB1_S2_HBox1 [this.fixed1]));
		w2.Position = 0;
		// Container child ZT_SVB1_S2_HBox1.Gtk.Box+BoxChild
		this.ZT_SVB1_S2_Button1 = new global::Gtk.Button ();
		this.ZT_SVB1_S2_Button1.WidthRequest = 200;
		this.ZT_SVB1_S2_Button1.CanFocus = true;
		this.ZT_SVB1_S2_Button1.Name = "ZT_SVB1_S2_Button1";
		this.ZT_SVB1_S2_Button1.UseUnderline = true;
		this.ZT_SVB1_S2_Button1.Label = global::Mono.Unix.Catalog.GetString ("New Project Config");
		this.ZT_SVB1_S2_HBox1.Add (this.ZT_SVB1_S2_Button1);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.ZT_SVB1_S2_HBox1 [this.ZT_SVB1_S2_Button1]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		// Container child ZT_SVB1_S2_HBox1.Gtk.Box+BoxChild
		this.fixed2 = new global::Gtk.Fixed ();
		this.fixed2.Name = "fixed2";
		this.fixed2.HasWindow = false;
		this.ZT_SVB1_S2_HBox1.Add (this.fixed2);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.ZT_SVB1_S2_HBox1 [this.fixed2]));
		w4.Position = 2;
		this.ZT_SubVBox1.Add (this.ZT_SVB1_S2_HBox1);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.ZT_SubVBox1 [this.ZT_SVB1_S2_HBox1]));
		w5.Position = 1;
		w5.Expand = false;
		w5.Fill = false;
		// Container child ZT_SubVBox1.Gtk.Box+BoxChild
		this.fixed11 = new global::Gtk.Fixed ();
		this.fixed11.HeightRequest = 50;
		this.fixed11.Name = "fixed11";
		this.fixed11.HasWindow = false;
		this.ZT_SubVBox1.Add (this.fixed11);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.ZT_SubVBox1 [this.fixed11]));
		w6.Position = 2;
		w6.Expand = false;
		w6.Fill = false;
		this.ZT_MainVBox1.Add (this.ZT_SubVBox1);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.ZT_MainVBox1 [this.ZT_SubVBox1]));
		w7.Position = 0;
		w7.Expand = false;
		w7.Fill = false;
		// Container child ZT_MainVBox1.Gtk.Box+BoxChild
		this.ZT_SubVBox2 = new global::Gtk.VBox ();
		this.ZT_SubVBox2.Name = "ZT_SubVBox2";
		this.ZT_SubVBox2.Spacing = 6;
		// Container child ZT_SubVBox2.Gtk.Box+BoxChild
		this.fixed9 = new global::Gtk.Fixed ();
		this.fixed9.HeightRequest = 50;
		this.fixed9.Name = "fixed9";
		this.fixed9.HasWindow = false;
		this.ZT_SubVBox2.Add (this.fixed9);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.ZT_SubVBox2 [this.fixed9]));
		w8.Position = 0;
		w8.Expand = false;
		w8.Fill = false;
		// Container child ZT_SubVBox2.Gtk.Box+BoxChild
		this.ZT_SVB2_S2_HBox1 = new global::Gtk.HBox ();
		this.ZT_SVB2_S2_HBox1.Name = "ZT_SVB2_S2_HBox1";
		this.ZT_SVB2_S2_HBox1.Spacing = 6;
		// Container child ZT_SVB2_S2_HBox1.Gtk.Box+BoxChild
		this.fixed4 = new global::Gtk.Fixed ();
		this.fixed4.Name = "fixed4";
		this.fixed4.HasWindow = false;
		this.ZT_SVB2_S2_HBox1.Add (this.fixed4);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.ZT_SVB2_S2_HBox1 [this.fixed4]));
		w9.Position = 0;
		// Container child ZT_SVB2_S2_HBox1.Gtk.Box+BoxChild
		this.ZT_SVB2_S2_Button1 = new global::Gtk.Button ();
		this.ZT_SVB2_S2_Button1.WidthRequest = 200;
		this.ZT_SVB2_S2_Button1.Sensitive = false;
		this.ZT_SVB2_S2_Button1.CanFocus = true;
		this.ZT_SVB2_S2_Button1.Name = "ZT_SVB2_S2_Button1";
		this.ZT_SVB2_S2_Button1.UseUnderline = true;
		this.ZT_SVB2_S2_Button1.Label = global::Mono.Unix.Catalog.GetString ("Create Daily Report");
		this.ZT_SVB2_S2_HBox1.Add (this.ZT_SVB2_S2_Button1);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.ZT_SVB2_S2_HBox1 [this.ZT_SVB2_S2_Button1]));
		w10.Position = 1;
		w10.Expand = false;
		w10.Fill = false;
		// Container child ZT_SVB2_S2_HBox1.Gtk.Box+BoxChild
		this.fixed5 = new global::Gtk.Fixed ();
		this.fixed5.Name = "fixed5";
		this.fixed5.HasWindow = false;
		this.ZT_SVB2_S2_HBox1.Add (this.fixed5);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.ZT_SVB2_S2_HBox1 [this.fixed5]));
		w11.Position = 2;
		this.ZT_SubVBox2.Add (this.ZT_SVB2_S2_HBox1);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.ZT_SubVBox2 [this.ZT_SVB2_S2_HBox1]));
		w12.Position = 1;
		w12.Expand = false;
		w12.Fill = false;
		// Container child ZT_SubVBox2.Gtk.Box+BoxChild
		this.fixed10 = new global::Gtk.Fixed ();
		this.fixed10.HeightRequest = 50;
		this.fixed10.Name = "fixed10";
		this.fixed10.HasWindow = false;
		this.ZT_SubVBox2.Add (this.fixed10);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.ZT_SubVBox2 [this.fixed10]));
		w13.Position = 2;
		w13.Expand = false;
		w13.Fill = false;
		this.ZT_MainVBox1.Add (this.ZT_SubVBox2);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.ZT_MainVBox1 [this.ZT_SubVBox2]));
		w14.Position = 1;
		w14.Expand = false;
		w14.Fill = false;
		// Container child ZT_MainVBox1.Gtk.Box+BoxChild
		this.ZT_SubVBox3 = new global::Gtk.VBox ();
		this.ZT_SubVBox3.Name = "ZT_SubVBox3";
		this.ZT_SubVBox3.Spacing = 6;
		// Container child ZT_SubVBox3.Gtk.Box+BoxChild
		this.fixed12 = new global::Gtk.Fixed ();
		this.fixed12.HeightRequest = 50;
		this.fixed12.Name = "fixed12";
		this.fixed12.HasWindow = false;
		this.ZT_SubVBox3.Add (this.fixed12);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.ZT_SubVBox3 [this.fixed12]));
		w15.Position = 0;
		w15.Expand = false;
		w15.Fill = false;
		// Container child ZT_SubVBox3.Gtk.Box+BoxChild
		this.ZT_SVB3_S2_HBox1 = new global::Gtk.HBox ();
		this.ZT_SVB3_S2_HBox1.Name = "ZT_SVB3_S2_HBox1";
		this.ZT_SVB3_S2_HBox1.Spacing = 6;
		// Container child ZT_SVB3_S2_HBox1.Gtk.Box+BoxChild
		this.fixed6 = new global::Gtk.Fixed ();
		this.fixed6.Name = "fixed6";
		this.fixed6.HasWindow = false;
		this.ZT_SVB3_S2_HBox1.Add (this.fixed6);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.ZT_SVB3_S2_HBox1 [this.fixed6]));
		w16.Position = 0;
		// Container child ZT_SVB3_S2_HBox1.Gtk.Box+BoxChild
		this.ZT_SVB3_S2_Button1 = new global::Gtk.Button ();
		this.ZT_SVB3_S2_Button1.WidthRequest = 200;
		this.ZT_SVB3_S2_Button1.Sensitive = false;
		this.ZT_SVB3_S2_Button1.CanFocus = true;
		this.ZT_SVB3_S2_Button1.Name = "ZT_SVB3_S2_Button1";
		this.ZT_SVB3_S2_Button1.UseUnderline = true;
		this.ZT_SVB3_S2_Button1.Label = global::Mono.Unix.Catalog.GetString ("Manage Project Configs");
		this.ZT_SVB3_S2_HBox1.Add (this.ZT_SVB3_S2_Button1);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.ZT_SVB3_S2_HBox1 [this.ZT_SVB3_S2_Button1]));
		w17.Position = 1;
		w17.Expand = false;
		w17.Fill = false;
		// Container child ZT_SVB3_S2_HBox1.Gtk.Box+BoxChild
		this.fixed7 = new global::Gtk.Fixed ();
		this.fixed7.Name = "fixed7";
		this.fixed7.HasWindow = false;
		this.ZT_SVB3_S2_HBox1.Add (this.fixed7);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.ZT_SVB3_S2_HBox1 [this.fixed7]));
		w18.Position = 2;
		this.ZT_SubVBox3.Add (this.ZT_SVB3_S2_HBox1);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.ZT_SubVBox3 [this.ZT_SVB3_S2_HBox1]));
		w19.Position = 1;
		w19.Expand = false;
		w19.Fill = false;
		// Container child ZT_SubVBox3.Gtk.Box+BoxChild
		this.fixed13 = new global::Gtk.Fixed ();
		this.fixed13.HeightRequest = 60;
		this.fixed13.Name = "fixed13";
		this.fixed13.HasWindow = false;
		this.ZT_SubVBox3.Add (this.fixed13);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.ZT_SubVBox3 [this.fixed13]));
		w20.Position = 2;
		w20.Expand = false;
		w20.Fill = false;
		this.ZT_MainVBox1.Add (this.ZT_SubVBox3);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.ZT_MainVBox1 [this.ZT_SubVBox3]));
		w21.Position = 2;
		w21.Expand = false;
		w21.Fill = false;
		this.Add (this.ZT_MainVBox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 600;
		this.DefaultHeight = 650;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.ZT_SVB1_S2_Button1.Clicked += new global::System.EventHandler (this.OnZTSVB1S2Button1Clicked);
	}
}
