
// This file has been generated by the GUI designer. Do not modify.
namespace Zester_Tool
{
	public partial class CreateConfig
	{
		private global::Gtk.VBox ZT_MainVBox1;
		
		private global::Gtk.VBox ZT_SubVBox1;
		
		private global::Gtk.HBox ZT_SubVBox1_HBox1;
		
		private global::Gtk.Label ZT_SubVBox1_Label1;
		
		private global::Gtk.Button ZT_SubVBox1_Button1;
		
		private global::Gtk.ScrolledWindow ZT_SubVBox1_Scrolled1;
		
		private global::Gtk.TextView ZT_SubVBox1_TextView1;
		
		private global::Gtk.VBox ZT_SubVBox2;
		
		private global::Gtk.Label ZT_SubVBox2_Label1;
		
		private global::Gtk.HBox ZT_SubVBox2_HBox1;
		
		private global::Gtk.RadioButton ZT_SubVBox2_Radio1;
		
		private global::Gtk.RadioButton ZT_SubVBox2_Radio2;
		
		private global::Gtk.VBox ZT_SubVBox3;
		
		private global::Gtk.Fixed ZT_SubVBox3_Space1;
		
		private global::Gtk.HBox ZT_SubVBox2_HBox2;
		
		private global::Gtk.Button ZT_SubVBox3_Button1;
		
		private global::Gtk.HSeparator ZT_SubVBox3_Separator1;
		
		private global::Gtk.Button ZT_SubVBox3_Button2;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Zester_Tool.CreateConfig
			this.WidthRequest = 600;
			this.HeightRequest = 650;
			this.Name = "Zester_Tool.CreateConfig";
			this.Title = global::Mono.Unix.Catalog.GetString ("Zester Tool : Create Config");
			this.Icon = global::Stetic.IconLoader.LoadIcon (this, "gtk-preferences", global::Gtk.IconSize.Menu);
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Resizable = false;
			this.AllowShrink = true;
			this.DestroyWithParent = true;
			this.Gravity = ((global::Gdk.Gravity)(10));
			// Container child Zester_Tool.CreateConfig.Gtk.Container+ContainerChild
			this.ZT_MainVBox1 = new global::Gtk.VBox ();
			this.ZT_MainVBox1.Name = "ZT_MainVBox1";
			this.ZT_MainVBox1.Spacing = 6;
			this.ZT_MainVBox1.BorderWidth = ((uint)(5));
			// Container child ZT_MainVBox1.Gtk.Box+BoxChild
			this.ZT_SubVBox1 = new global::Gtk.VBox ();
			this.ZT_SubVBox1.Name = "ZT_SubVBox1";
			this.ZT_SubVBox1.Spacing = 6;
			// Container child ZT_SubVBox1.Gtk.Box+BoxChild
			this.ZT_SubVBox1_HBox1 = new global::Gtk.HBox ();
			this.ZT_SubVBox1_HBox1.Name = "ZT_SubVBox1_HBox1";
			this.ZT_SubVBox1_HBox1.Spacing = 6;
			// Container child ZT_SubVBox1_HBox1.Gtk.Box+BoxChild
			this.ZT_SubVBox1_Label1 = new global::Gtk.Label ();
			this.ZT_SubVBox1_Label1.Name = "ZT_SubVBox1_Label1";
			this.ZT_SubVBox1_Label1.Xalign = 0.02F;
			this.ZT_SubVBox1_Label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Config save location:");
			this.ZT_SubVBox1_HBox1.Add (this.ZT_SubVBox1_Label1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.ZT_SubVBox1_HBox1 [this.ZT_SubVBox1_Label1]));
			w1.Position = 0;
			// Container child ZT_SubVBox1_HBox1.Gtk.Box+BoxChild
			this.ZT_SubVBox1_Button1 = new global::Gtk.Button ();
			this.ZT_SubVBox1_Button1.CanFocus = true;
			this.ZT_SubVBox1_Button1.Name = "ZT_SubVBox1_Button1";
			this.ZT_SubVBox1_Button1.UseUnderline = true;
			this.ZT_SubVBox1_Button1.Label = global::Mono.Unix.Catalog.GetString ("Edit Save Location");
			this.ZT_SubVBox1_HBox1.Add (this.ZT_SubVBox1_Button1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.ZT_SubVBox1_HBox1 [this.ZT_SubVBox1_Button1]));
			w2.Position = 1;
			this.ZT_SubVBox1.Add (this.ZT_SubVBox1_HBox1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.ZT_SubVBox1 [this.ZT_SubVBox1_HBox1]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child ZT_SubVBox1.Gtk.Box+BoxChild
			this.ZT_SubVBox1_Scrolled1 = new global::Gtk.ScrolledWindow ();
			this.ZT_SubVBox1_Scrolled1.HeightRequest = 100;
			this.ZT_SubVBox1_Scrolled1.Name = "ZT_SubVBox1_Scrolled1";
			this.ZT_SubVBox1_Scrolled1.HscrollbarPolicy = ((global::Gtk.PolicyType)(2));
			this.ZT_SubVBox1_Scrolled1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child ZT_SubVBox1_Scrolled1.Gtk.Container+ContainerChild
			this.ZT_SubVBox1_TextView1 = new global::Gtk.TextView ();
			this.ZT_SubVBox1_TextView1.CanFocus = true;
			this.ZT_SubVBox1_TextView1.Name = "ZT_SubVBox1_TextView1";
			this.ZT_SubVBox1_TextView1.Editable = false;
			this.ZT_SubVBox1_TextView1.CursorVisible = false;
			this.ZT_SubVBox1_TextView1.AcceptsTab = false;
			this.ZT_SubVBox1_TextView1.WrapMode = ((global::Gtk.WrapMode)(1));
			this.ZT_SubVBox1_Scrolled1.Add (this.ZT_SubVBox1_TextView1);
			this.ZT_SubVBox1.Add (this.ZT_SubVBox1_Scrolled1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.ZT_SubVBox1 [this.ZT_SubVBox1_Scrolled1]));
			w5.Position = 1;
			w5.Expand = false;
			this.ZT_MainVBox1.Add (this.ZT_SubVBox1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.ZT_MainVBox1 [this.ZT_SubVBox1]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child ZT_MainVBox1.Gtk.Box+BoxChild
			this.ZT_SubVBox2 = new global::Gtk.VBox ();
			this.ZT_SubVBox2.Name = "ZT_SubVBox2";
			this.ZT_SubVBox2.Spacing = 6;
			// Container child ZT_SubVBox2.Gtk.Box+BoxChild
			this.ZT_SubVBox2_Label1 = new global::Gtk.Label ();
			this.ZT_SubVBox2_Label1.Name = "ZT_SubVBox2_Label1";
			this.ZT_SubVBox2_Label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Template style:");
			this.ZT_SubVBox2.Add (this.ZT_SubVBox2_Label1);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.ZT_SubVBox2 [this.ZT_SubVBox2_Label1]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child ZT_SubVBox2.Gtk.Box+BoxChild
			this.ZT_SubVBox2_HBox1 = new global::Gtk.HBox ();
			this.ZT_SubVBox2_HBox1.Name = "ZT_SubVBox2_HBox1";
			this.ZT_SubVBox2_HBox1.Spacing = 6;
			// Container child ZT_SubVBox2_HBox1.Gtk.Box+BoxChild
			this.ZT_SubVBox2_Radio1 = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Normal"));
			this.ZT_SubVBox2_Radio1.CanFocus = true;
			this.ZT_SubVBox2_Radio1.Name = "ZT_SubVBox2_Radio1";
			this.ZT_SubVBox2_Radio1.DrawIndicator = true;
			this.ZT_SubVBox2_Radio1.UseUnderline = true;
			this.ZT_SubVBox2_Radio1.Group = new global::GLib.SList (global::System.IntPtr.Zero);
			this.ZT_SubVBox2_HBox1.Add (this.ZT_SubVBox2_Radio1);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.ZT_SubVBox2_HBox1 [this.ZT_SubVBox2_Radio1]));
			w8.Position = 0;
			w8.Fill = false;
			// Container child ZT_SubVBox2_HBox1.Gtk.Box+BoxChild
			this.ZT_SubVBox2_Radio2 = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Scripting / Planing"));
			this.ZT_SubVBox2_Radio2.CanFocus = true;
			this.ZT_SubVBox2_Radio2.Name = "ZT_SubVBox2_Radio2";
			this.ZT_SubVBox2_Radio2.DrawIndicator = true;
			this.ZT_SubVBox2_Radio2.UseUnderline = true;
			this.ZT_SubVBox2_Radio2.Group = this.ZT_SubVBox2_Radio1.Group;
			this.ZT_SubVBox2_HBox1.Add (this.ZT_SubVBox2_Radio2);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.ZT_SubVBox2_HBox1 [this.ZT_SubVBox2_Radio2]));
			w9.Position = 1;
			w9.Fill = false;
			this.ZT_SubVBox2.Add (this.ZT_SubVBox2_HBox1);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.ZT_SubVBox2 [this.ZT_SubVBox2_HBox1]));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			this.ZT_MainVBox1.Add (this.ZT_SubVBox2);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.ZT_MainVBox1 [this.ZT_SubVBox2]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			// Container child ZT_MainVBox1.Gtk.Box+BoxChild
			this.ZT_SubVBox3 = new global::Gtk.VBox ();
			this.ZT_SubVBox3.Name = "ZT_SubVBox3";
			this.ZT_SubVBox3.Spacing = 6;
			// Container child ZT_SubVBox3.Gtk.Box+BoxChild
			this.ZT_SubVBox3_Space1 = new global::Gtk.Fixed ();
			this.ZT_SubVBox3_Space1.HeightRequest = 390;
			this.ZT_SubVBox3_Space1.Name = "ZT_SubVBox3_Space1";
			this.ZT_SubVBox3_Space1.HasWindow = false;
			this.ZT_SubVBox3.Add (this.ZT_SubVBox3_Space1);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.ZT_SubVBox3 [this.ZT_SubVBox3_Space1]));
			w12.Position = 0;
			// Container child ZT_SubVBox3.Gtk.Box+BoxChild
			this.ZT_SubVBox2_HBox2 = new global::Gtk.HBox ();
			this.ZT_SubVBox2_HBox2.Name = "ZT_SubVBox2_HBox2";
			this.ZT_SubVBox2_HBox2.Spacing = 6;
			// Container child ZT_SubVBox2_HBox2.Gtk.Box+BoxChild
			this.ZT_SubVBox3_Button1 = new global::Gtk.Button ();
			this.ZT_SubVBox3_Button1.WidthRequest = 100;
			this.ZT_SubVBox3_Button1.CanFocus = true;
			this.ZT_SubVBox3_Button1.Name = "ZT_SubVBox3_Button1";
			this.ZT_SubVBox3_Button1.UseUnderline = true;
			this.ZT_SubVBox3_Button1.Label = global::Mono.Unix.Catalog.GetString ("Main Menu");
			this.ZT_SubVBox2_HBox2.Add (this.ZT_SubVBox3_Button1);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.ZT_SubVBox2_HBox2 [this.ZT_SubVBox3_Button1]));
			w13.Position = 0;
			w13.Expand = false;
			w13.Fill = false;
			// Container child ZT_SubVBox2_HBox2.Gtk.Box+BoxChild
			this.ZT_SubVBox3_Separator1 = new global::Gtk.HSeparator ();
			this.ZT_SubVBox3_Separator1.Name = "ZT_SubVBox3_Separator1";
			this.ZT_SubVBox2_HBox2.Add (this.ZT_SubVBox3_Separator1);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.ZT_SubVBox2_HBox2 [this.ZT_SubVBox3_Separator1]));
			w14.Position = 1;
			// Container child ZT_SubVBox2_HBox2.Gtk.Box+BoxChild
			this.ZT_SubVBox3_Button2 = new global::Gtk.Button ();
			this.ZT_SubVBox3_Button2.WidthRequest = 100;
			this.ZT_SubVBox3_Button2.CanFocus = true;
			this.ZT_SubVBox3_Button2.Name = "ZT_SubVBox3_Button2";
			this.ZT_SubVBox3_Button2.UseUnderline = true;
			this.ZT_SubVBox3_Button2.Label = global::Mono.Unix.Catalog.GetString ("Next");
			this.ZT_SubVBox2_HBox2.Add (this.ZT_SubVBox3_Button2);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.ZT_SubVBox2_HBox2 [this.ZT_SubVBox3_Button2]));
			w15.Position = 2;
			w15.Expand = false;
			w15.Fill = false;
			this.ZT_SubVBox3.Add (this.ZT_SubVBox2_HBox2);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.ZT_SubVBox3 [this.ZT_SubVBox2_HBox2]));
			w16.Position = 1;
			w16.Expand = false;
			w16.Fill = false;
			this.ZT_MainVBox1.Add (this.ZT_SubVBox3);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.ZT_MainVBox1 [this.ZT_SubVBox3]));
			w17.Position = 2;
			w17.Expand = false;
			w17.Fill = false;
			this.Add (this.ZT_MainVBox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 600;
			this.DefaultHeight = 650;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.ZT_SubVBox1_Button1.Clicked += new global::System.EventHandler (this.OnZTSubVBox1Button1Clicked);
			this.ZT_SubVBox3_Button2.Clicked += new global::System.EventHandler (this.OnZTSubVBox3Button2Clicked);
		}
	}
}
