
// This file has been generated by the GUI designer. Do not modify.
namespace Zester_Tool
{
	public partial class SaveDialog
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Zester_Tool.SaveDialog
			this.Name = "Zester_Tool.SaveDialog";
			this.Title = global::Mono.Unix.Catalog.GetString ("SaveDialog");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
