
// This file has been generated by the GUI designer. Do not modify.
namespace Zester_Tool
{
	public partial class EnvironmentChooser
	{
		private global::Gtk.VBox ZT_VBox1;
		private global::Gtk.Entry entry1;
		private global::Gtk.HBox ZT_SubBox1_HBox1;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TreeView EnvironTree_Main;
		private global::Gtk.VBox ZT_SubBox1a_VBox1;
		private global::Gtk.Button button1;
		private global::Gtk.Label label1;
		private global::Gtk.Fixed fixed2;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Zester_Tool.EnvironmentChooser
			this.WidthRequest = 1000;
			this.HeightRequest = 650;
			this.Name = "Zester_Tool.EnvironmentChooser";
			this.Title = global::Mono.Unix.Catalog.GetString ("Zester Tool : Environment Chooser");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.BorderWidth = ((uint)(5));
			this.Resizable = false;
			this.AllowShrink = true;
			this.DestroyWithParent = true;
			// Container child Zester_Tool.EnvironmentChooser.Gtk.Container+ContainerChild
			this.ZT_VBox1 = new global::Gtk.VBox ();
			this.ZT_VBox1.Name = "ZT_VBox1";
			this.ZT_VBox1.Spacing = 6;
			// Container child ZT_VBox1.Gtk.Box+BoxChild
			this.entry1 = new global::Gtk.Entry ();
			this.entry1.CanFocus = true;
			this.entry1.Name = "entry1";
			this.entry1.Text = global::Mono.Unix.Catalog.GetString ("Enter text here");
			this.entry1.IsEditable = true;
			this.entry1.MaxLength = 50;
			this.entry1.InvisibleChar = '●';
			this.ZT_VBox1.Add (this.entry1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.ZT_VBox1 [this.entry1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child ZT_VBox1.Gtk.Box+BoxChild
			this.ZT_SubBox1_HBox1 = new global::Gtk.HBox ();
			this.ZT_SubBox1_HBox1.WidthRequest = 700;
			this.ZT_SubBox1_HBox1.Name = "ZT_SubBox1_HBox1";
			this.ZT_SubBox1_HBox1.Spacing = 6;
			// Container child ZT_SubBox1_HBox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.WidthRequest = 500;
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.EnvironTree_Main = new global::Gtk.TreeView ();
			this.EnvironTree_Main.CanFocus = true;
			this.EnvironTree_Main.Name = "EnvironTree_Main";
			this.EnvironTree_Main.EnableSearch = false;
			this.GtkScrolledWindow.Add (this.EnvironTree_Main);
			this.ZT_SubBox1_HBox1.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.ZT_SubBox1_HBox1 [this.GtkScrolledWindow]));
			w3.Position = 0;
			// Container child ZT_SubBox1_HBox1.Gtk.Box+BoxChild
			this.ZT_SubBox1a_VBox1 = new global::Gtk.VBox ();
			this.ZT_SubBox1a_VBox1.Name = "ZT_SubBox1a_VBox1";
			this.ZT_SubBox1a_VBox1.Spacing = 6;
			// Container child ZT_SubBox1a_VBox1.Gtk.Box+BoxChild
			this.button1 = new global::Gtk.Button ();
			this.button1.WidthRequest = 300;
			this.button1.CanFocus = true;
			this.button1.Name = "button1";
			this.button1.UseUnderline = true;
			this.button1.Label = global::Mono.Unix.Catalog.GetString ("Search");
			this.ZT_SubBox1a_VBox1.Add (this.button1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.ZT_SubBox1a_VBox1 [this.button1]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child ZT_SubBox1a_VBox1.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.HeightRequest = 100;
			this.label1.Name = "label1";
			this.label1.Wrap = true;
			this.ZT_SubBox1a_VBox1.Add (this.label1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.ZT_SubBox1a_VBox1 [this.label1]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			this.ZT_SubBox1_HBox1.Add (this.ZT_SubBox1a_VBox1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.ZT_SubBox1_HBox1 [this.ZT_SubBox1a_VBox1]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			this.ZT_VBox1.Add (this.ZT_SubBox1_HBox1);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.ZT_VBox1 [this.ZT_SubBox1_HBox1]));
			w7.Position = 1;
			// Container child ZT_VBox1.Gtk.Box+BoxChild
			this.fixed2 = new global::Gtk.Fixed ();
			this.fixed2.WidthRequest = 0;
			this.fixed2.HeightRequest = 50;
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			this.ZT_VBox1.Add (this.fixed2);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.ZT_VBox1 [this.fixed2]));
			w8.Position = 2;
			w8.Expand = false;
			w8.Fill = false;
			this.Add (this.ZT_VBox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 1000;
			this.DefaultHeight = 650;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.button1.Clicked += new global::System.EventHandler (this.OnButton1Clicked);
		}
	}
}
